name: Build docker images with assets

on:
  workflow_dispatch:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: truelecter/tg-haiku-bot

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build base image
      uses: docker/build-push-action@v2
      with:
        push: true
        file: Dockerfile
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
